import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("AI preview prompt uses richer business context and requested variant count", async () => {
  const prompts = await readFile("src/lib/ai/prompts.ts", "utf8");
  const generator = await readFile("src/lib/ai/generate-copy.ts", "utf8");
  const generateRoute = await readFile("src/app/api/generate-copy/route.ts", "utf8");
  const regenerateRoute = await readFile("src/app/api/regenerate-copy/route.ts", "utf8");

  for (const [name, source] of [
    ["prompts", prompts],
    ["generator", generator],
    ["generate route", generateRoute],
    ["regenerate route", regenerateRoute],
  ]) {
    assert.match(source, /variantCount/, `${name} should support variable copy variant counts`);
  }

  assert.match(prompts, /SOCIAL PROOF/, "prompt should include review/rating context");
  assert.match(prompts, /BOOKING SIGNALS/, "prompt should include booking availability context");
  assert.match(prompts, /BUSINESS HOURS/, "prompt should include hours context");
  assert.match(generateRoute, /socialProof:/, "create flow should pass social proof into AI generation");
  assert.match(regenerateRoute, /socialProof:/, "regenerate flow should preserve social proof for AI generation");
});

test("preview edit and regenerate preserve the owner's original description", async () => {
  const generateRoute = await readFile("src/app/api/generate-copy/route.ts", "utf8");
  const regenerateRoute = await readFile("src/app/api/regenerate-copy/route.ts", "utf8");
  const previewDataRoute = await readFile("src/app/api/preview-data/route.ts", "utf8");

  assert.match(generateRoute, /business_description:\s*description/, "create flow should store original business description metadata");
  assert.match(regenerateRoute, /currentCopy\.business_description/, "regenerate should reuse original business description");
  assert.match(previewDataRoute, /business_description/, "edit flow should return the stored business description");
  assert.doesNotMatch(previewDataRoute, /description:\s*""/, "edit flow should not discard business description");
});

test("product descriptions generated by AI are rendered in templates", async () => {
  const types = await readFile("src/lib/ai/types.ts", "utf8");
  const orchestrator = await readFile("src/components/templates/TemplateOrchestrator.tsx", "utf8");

  assert.match(types, /product_descriptions\?:\s*Record<string, string>/, "GeneratedCopy should type product descriptions");
  assert.match(orchestrator, /copy\?\.product_descriptions\?\.\[p\.name\]/, "products should merge generated product descriptions");
  assert.match(orchestrator, /products=\{products\}/, "templates should receive enriched products");
});

test("preview compare and wizard help users choose stronger preview inputs", async () => {
  const compare = await readFile("src/app/(marketing)/preview/compare/[groupId]/CompareClient.tsx", "utf8");
  const wizard = await readFile("src/app/(marketing)/preview/page.tsx", "utf8");

  assert.match(compare, /runway:\s*\{/, "compare screen should describe Runway previews");
  assert.match(wizard, /getPreviewQualityTips/, "wizard should compute preview quality guidance");
  assert.match(wizard, /Preview quality tips/, "wizard should show quality tips before generation");
});
