"use client";
import { useEffect, useId, useRef } from "react";
import { useTranslations } from "next-intl";
import type { ServiceItem } from "@/lib/ai/types"; import type { ThemeColors } from "@/lib/templates/themes";
import type { EstimateDeliveryMode, EstimateModalState } from "./estimate-modal-state";
import { HomeServicesEstimateForm } from "./HomeServicesEstimateForm";
export function HomeServicesEstimateModal({state,services,colors,deliveryMode,onClose,onComplete}:{state:EstimateModalState;services:ServiceItem[];colors:ThemeColors;deliveryMode:EstimateDeliveryMode;onClose:()=>void;onComplete:()=>void}) { const t=useTranslations("homeServices"); const title=useId(); const box=useRef<HTMLDivElement>(null); const prior=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(!state.open)return; prior.current=document.activeElement as HTMLElement; const old=document.body.style.overflow; document.body.style.overflow="hidden"; box.current?.focus(); const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose(); if(e.key==="Tab"){const nodes=box.current?.querySelectorAll<HTMLElement>('button,input,select,textarea,[href]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=old;document.removeEventListener("keydown",key);prior.current?.focus()}},[state.open,onClose]); if(!state.open)return null;
 return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/55 p-0 sm:items-center sm:p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div ref={box} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={title} className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl p-5 outline-none sm:max-w-xl sm:rounded-3xl sm:p-7" style={{backgroundColor:colors.background}}><div className="mb-5 flex justify-between gap-3"><h2 id={title} className="text-2xl font-bold">{state.completed?t(deliveryMode==="preview_mock"?"estimate.modal.sampleSuccessTitle":"estimate.success.title"):t("estimate.modal.title")}</h2><button onClick={onClose} aria-label={t("estimate.modal.close")} className="h-11 w-11">✕</button></div>{state.completed?<div role="status"><p>{t(deliveryMode==="preview_mock"?"estimate.modal.sampleSuccessBody":"estimate.success.body")}</p><button className="mt-6 min-h-11 rounded-full px-5" style={{backgroundColor:colors.secondary}} onClick={onClose}>{t("estimate.modal.close")}</button></div>:<HomeServicesEstimateForm services={services} service={state.service} colors={colors} deliveryMode={deliveryMode} onComplete={onComplete}/>}</div></div> }
