export { TemplateHero } from "./TemplateHero";
export { TemplateServices } from "./TemplateServices";
export { TemplateGallery } from "./TemplateGallery";
export { TemplateAbout } from "./TemplateAbout";
export { TemplateBooking } from "./TemplateBooking";
export { TemplateContact } from "./TemplateContact";
export { TemplateMap } from "./TemplateMap";
export { TemplateFooter } from "./TemplateFooter";
export { TemplateRenderer } from "./TemplateRenderer";
