import type { BusinessType, ColorTheme } from '@/lib/ai/types';

export interface ThemeColors {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  foreground: string;
  muted: string;
}

export interface ThemeConfig {
  id: ColorTheme;
  name: string;
  colors: ThemeColors;
  previewSwatch: [string, string, string]; // 3 colors shown in picker
}

export const THEMES_BY_VERTICAL: Record<BusinessType, ThemeConfig[]> = {
  salon: [
    {
      id: 'salon_gold',
      name: 'Gold & Cream',
      colors: {
        primary: '#B8860B',
        secondary: '#FFFDD0',
        accent: '#DAA520',
        background: '#FFF8F0',
        foreground: '#2D2017',
        muted: '#F5E6D3',
      },
      previewSwatch: ['#B8860B', '#FFFDD0', '#FFF8F0'],
    },
    {
      id: 'salon_rose',
      name: 'Rose & Blush',
      colors: {
        primary: '#C48B9F',
        secondary: '#F8E8EE',
        accent: '#D4A0A0',
        background: '#FFF5F7',
        foreground: '#3D2B2B',
        muted: '#F5E0E7',
      },
      previewSwatch: ['#C48B9F', '#F8E8EE', '#FFF5F7'],
    },
    {
      id: 'salon_mocha',
      name: 'Mocha & Earth',
      colors: {
        primary: '#6B4226',
        secondary: '#D4B896',
        accent: '#8B6914',
        background: '#FAF6F1',
        foreground: '#2C1810',
        muted: '#E8DDD0',
      },
      previewSwatch: ['#6B4226', '#D4B896', '#FAF6F1'],
    },
    {
      id: 'salon_lavender',
      name: 'Lavender & Sage',
      colors: {
        primary: '#7B68AE',
        secondary: '#D4E2D4',
        accent: '#9B8EC4',
        background: '#FAF8FF',
        foreground: '#2D2540',
        muted: '#EDE8F5',
      },
      previewSwatch: ['#7B68AE', '#D4E2D4', '#FAF8FF'],
    },
    {
      id: 'salon_midnight',
      name: 'Midnight Glam',
      colors: {
        primary: '#E8B4B8',
        secondary: '#1A1A2E',
        accent: '#F0C4C8',
        background: '#16213E',
        foreground: '#F5F0F0',
        muted: '#2A2A4A',
      },
      previewSwatch: ['#E8B4B8', '#1A1A2E', '#16213E'],
    },
    {
      id: 'salon_emerald',
      name: 'Emerald & Ivory',
      colors: {
        primary: '#2E8B57',
        secondary: '#FFFFF0',
        accent: '#3CB371',
        background: '#F8FFF8',
        foreground: '#1A3020',
        muted: '#E0F0E0',
      },
      previewSwatch: ['#2E8B57', '#FFFFF0', '#F8FFF8'],
    },
    {
      id: 'salon_peach',
      name: 'Peach & Copper',
      colors: {
        primary: '#E8927C',
        secondary: '#B87333',
        accent: '#F0A090',
        background: '#FFF5F0',
        foreground: '#3A1A10',
        muted: '#F5E0D5',
      },
      previewSwatch: ['#E8927C', '#B87333', '#FFF5F0'],
    },
    {
      id: 'salon_noir',
      name: 'Noir & Pearl',
      colors: {
        primary: '#F0E6D3',
        secondary: '#1A1A1A',
        accent: '#D4C5A9',
        background: '#111111',
        foreground: '#F5F0E8',
        muted: '#2A2A2A',
      },
      previewSwatch: ['#F0E6D3', '#1A1A1A', '#111111'],
    },
  ],
  barbershop: [
    {
      id: 'barbershop_black_gold',
      name: 'Black & Gold',
      colors: {
        primary: '#D4AF37',
        secondary: '#1A1A1A',
        accent: '#FFD700',
        background: '#0D0D0D',
        foreground: '#F5F5F5',
        muted: '#2A2A2A',
      },
      previewSwatch: ['#D4AF37', '#1A1A1A', '#0D0D0D'],
    },
    {
      id: 'barbershop_navy',
      name: 'Navy & Silver',
      colors: {
        primary: '#1B3A5C',
        secondary: '#C0C0C0',
        accent: '#4A90D9',
        background: '#F0F4F8',
        foreground: '#0D1B2A',
        muted: '#D6E4F0',
      },
      previewSwatch: ['#1B3A5C', '#C0C0C0', '#F0F4F8'],
    },
    {
      id: 'barbershop_forest',
      name: 'Forest & Tan',
      colors: {
        primary: '#2D5016',
        secondary: '#D2B48C',
        accent: '#4A7C23',
        background: '#F5F2EB',
        foreground: '#1A2E0A',
        muted: '#E0D8C8',
      },
      previewSwatch: ['#2D5016', '#D2B48C', '#F5F2EB'],
    },
    {
      id: 'barbershop_burgundy',
      name: 'Burgundy & Cream',
      colors: {
        primary: '#800020',
        secondary: '#F5F0E8',
        accent: '#A0153E',
        background: '#FFF8F2',
        foreground: '#1A0008',
        muted: '#F0E0D0',
      },
      previewSwatch: ['#800020', '#F5F0E8', '#FFF8F2'],
    },
    {
      id: 'barbershop_charcoal',
      name: 'Charcoal & Copper',
      colors: {
        primary: '#B87333',
        secondary: '#2C2C2C',
        accent: '#D4956A',
        background: '#1C1C1C',
        foreground: '#E8E0D8',
        muted: '#3A3A3A',
      },
      previewSwatch: ['#B87333', '#2C2C2C', '#1C1C1C'],
    },
    {
      id: 'barbershop_slate',
      name: 'Slate & Amber',
      colors: {
        primary: '#F0A500',
        secondary: '#3D4F5F',
        accent: '#FFB830',
        background: '#2C3E50',
        foreground: '#ECF0F1',
        muted: '#3D4F5F',
      },
      previewSwatch: ['#F0A500', '#3D4F5F', '#2C3E50'],
    },
    {
      id: 'barbershop_vintage',
      name: 'Vintage Red',
      colors: {
        primary: '#C0392B',
        secondary: '#F5E6D3',
        accent: '#E74C3C',
        background: '#FAF5EF',
        foreground: '#2C1A10',
        muted: '#F0DCC8',
      },
      previewSwatch: ['#C0392B', '#F5E6D3', '#FAF5EF'],
    },
    {
      id: 'barbershop_ice',
      name: 'Ice & Steel',
      colors: {
        primary: '#00B4D8',
        secondary: '#1B2838',
        accent: '#48CAE4',
        background: '#0D1B2A',
        foreground: '#E0F0FF',
        muted: '#1B3A4B',
      },
      previewSwatch: ['#00B4D8', '#1B2838', '#0D1B2A'],
    },
  ],
  restaurant: [
    {
      id: 'restaurant_burgundy',
      name: 'Burgundy & Cream',
      colors: {
        primary: '#722F37',
        secondary: '#FFFDD0',
        accent: '#A0522D',
        background: '#FFF8F0',
        foreground: '#2C1018',
        muted: '#F2E0D0',
      },
      previewSwatch: ['#722F37', '#FFFDD0', '#FFF8F0'],
    },
    {
      id: 'restaurant_olive',
      name: 'Olive & Warm',
      colors: {
        primary: '#556B2F',
        secondary: '#F0E68C',
        accent: '#8B7D3C',
        background: '#FAFAF0',
        foreground: '#2A2E1A',
        muted: '#E8E4C8',
      },
      previewSwatch: ['#556B2F', '#F0E68C', '#FAFAF0'],
    },
    {
      id: 'restaurant_ocean',
      name: 'Ocean & Sand',
      colors: {
        primary: '#1E6091',
        secondary: '#F5DEB3',
        accent: '#2E86C1',
        background: '#FAF8F5',
        foreground: '#0A2E4A',
        muted: '#E0E8EF',
      },
      previewSwatch: ['#1E6091', '#F5DEB3', '#FAF8F5'],
    },
    {
      id: 'restaurant_terracotta',
      name: 'Terracotta & Herb',
      colors: {
        primary: '#C4632A',
        secondary: '#4A7C59',
        accent: '#E07B39',
        background: '#FFF9F2',
        foreground: '#2C1608',
        muted: '#F0E4D4',
      },
      previewSwatch: ['#C4632A', '#4A7C59', '#FFF9F2'],
    },
    {
      id: 'restaurant_midnight',
      name: 'Midnight & Amber',
      colors: {
        primary: '#D4A017',
        secondary: '#1A1A2E',
        accent: '#E8B830',
        background: '#0F0F1A',
        foreground: '#F5F0E0',
        muted: '#2A2A3E',
      },
      previewSwatch: ['#D4A017', '#1A1A2E', '#0F0F1A'],
    },
    {
      id: 'restaurant_sage',
      name: 'Sage & Linen',
      colors: {
        primary: '#87A878',
        secondary: '#FAF0E6',
        accent: '#6B8E5B',
        background: '#FAFAF5',
        foreground: '#2A3520',
        muted: '#E8E0D0',
      },
      previewSwatch: ['#87A878', '#FAF0E6', '#FAFAF5'],
    },
    {
      id: 'restaurant_fire',
      name: 'Fire & Smoke',
      colors: {
        primary: '#FF4500',
        secondary: '#2C2C2C',
        accent: '#FF6347',
        background: '#1A1A1A',
        foreground: '#F5F0E8',
        muted: '#3A3A3A',
      },
      previewSwatch: ['#FF4500', '#2C2C2C', '#1A1A1A'],
    },
    {
      id: 'restaurant_noir',
      name: 'Noir & Gold',
      colors: {
        primary: '#C9A84C',
        secondary: '#0A0A0A',
        accent: '#E0C068',
        background: '#0F0F0F',
        foreground: '#F5F0E0',
        muted: '#252525',
      },
      previewSwatch: ['#C9A84C', '#0A0A0A', '#0F0F0F'],
    },
  ],
  nails: [
    {
      id: 'nails_pink',
      name: 'Pink & Lavender',
      colors: {
        primary: '#FF69B4',
        secondary: '#E6E6FA',
        accent: '#DA70D6',
        background: '#FFF5FA',
        foreground: '#4A1942',
        muted: '#F5E6F5',
      },
      previewSwatch: ['#FF69B4', '#E6E6FA', '#FFF5FA'],
    },
    {
      id: 'nails_coral',
      name: 'Coral & Mint',
      colors: {
        primary: '#FF7F50',
        secondary: '#98FFB3',
        accent: '#FF6347',
        background: '#F5FFFA',
        foreground: '#2D1A14',
        muted: '#E0F5E8',
      },
      previewSwatch: ['#FF7F50', '#98FFB3', '#F5FFFA'],
    },
    {
      id: 'nails_berry',
      name: 'Berry & Gold',
      colors: {
        primary: '#8B008B',
        secondary: '#FFD700',
        accent: '#C71585',
        background: '#FFF8F5',
        foreground: '#2D0A2D',
        muted: '#F0E0F0',
      },
      previewSwatch: ['#8B008B', '#FFD700', '#FFF8F5'],
    },
    {
      id: 'nails_rose_gold',
      name: 'Rose Gold & Marble',
      colors: {
        primary: '#B76E79',
        secondary: '#F5F0EC',
        accent: '#D4A0A7',
        background: '#FFFAF8',
        foreground: '#3D2025',
        muted: '#F0E4E0',
      },
      previewSwatch: ['#B76E79', '#F5F0EC', '#FFFAF8'],
    },
    {
      id: 'nails_midnight',
      name: 'Midnight & Neon',
      colors: {
        primary: '#FF1493',
        secondary: '#0D0D2B',
        accent: '#00FFFF',
        background: '#0A0A1A',
        foreground: '#F5F0FF',
        muted: '#1A1A3A',
      },
      previewSwatch: ['#FF1493', '#0D0D2B', '#0A0A1A'],
    },
    {
      id: 'nails_seafoam',
      name: 'Seafoam & Blush',
      colors: {
        primary: '#66CDAA',
        secondary: '#FFE4E1',
        accent: '#48D1CC',
        background: '#F5FFFA',
        foreground: '#1A3A35',
        muted: '#E0F5F0',
      },
      previewSwatch: ['#66CDAA', '#FFE4E1', '#F5FFFA'],
    },
    {
      id: 'nails_lilac',
      name: 'Lilac Dreams',
      colors: {
        primary: '#9B7EC8',
        secondary: '#FFF0F5',
        accent: '#B88ED0',
        background: '#FAF5FF',
        foreground: '#2D1845',
        muted: '#EDE0F5',
      },
      previewSwatch: ['#9B7EC8', '#FFF0F5', '#FAF5FF'],
    },
    {
      id: 'nails_champagne',
      name: 'Champagne & Noir',
      colors: {
        primary: '#D4AF37',
        secondary: '#1A1A1A',
        accent: '#F0D060',
        background: '#0D0D0D',
        foreground: '#F5F0E0',
        muted: '#2A2520',
      },
      previewSwatch: ['#D4AF37', '#1A1A1A', '#0D0D0D'],
    },
  ],
  braids: [
    {
      id: 'braids_kente',
      name: 'Kente Gold',
      colors: {
        primary: '#DAA520',
        secondary: '#228B22',
        accent: '#FF4500',
        background: '#FFF8E7',
        foreground: '#2A1F00',
        muted: '#F0E8C8',
      },
      previewSwatch: ['#DAA520', '#228B22', '#FFF8E7'],
    },
    {
      id: 'braids_royal',
      name: 'Royal Purple',
      colors: {
        primary: '#6A0DAD',
        secondary: '#FFD700',
        accent: '#9B59B6',
        background: '#FAF5FF',
        foreground: '#1A0030',
        muted: '#E8D5F5',
      },
      previewSwatch: ['#6A0DAD', '#FFD700', '#FAF5FF'],
    },
    {
      id: 'braids_earth',
      name: 'Earth & Terracotta',
      colors: {
        primary: '#A0522D',
        secondary: '#DEB887',
        accent: '#CD853F',
        background: '#FDF5E6',
        foreground: '#3E1A00',
        muted: '#E8D8C4',
      },
      previewSwatch: ['#A0522D', '#DEB887', '#FDF5E6'],
    },
    {
      id: 'braids_ocean',
      name: 'Ocean & Teal',
      colors: {
        primary: '#008080',
        secondary: '#E0F0F0',
        accent: '#20B2AA',
        background: '#F0FAFA',
        foreground: '#003030',
        muted: '#D0E8E8',
      },
      previewSwatch: ['#008080', '#E0F0F0', '#F0FAFA'],
    },
    {
      id: 'braids_sunset',
      name: 'Sunset & Bronze',
      colors: {
        primary: '#CD7F32',
        secondary: '#FF6B35',
        accent: '#E8963E',
        background: '#FFF5EB',
        foreground: '#2A1A08',
        muted: '#F5E0C8',
      },
      previewSwatch: ['#CD7F32', '#FF6B35', '#FFF5EB'],
    },
    {
      id: 'braids_midnight',
      name: 'Midnight & Gold',
      colors: {
        primary: '#FFD700',
        secondary: '#0D0D20',
        accent: '#FFC107',
        background: '#0A0A18',
        foreground: '#F5F0E0',
        muted: '#1A1A30',
      },
      previewSwatch: ['#FFD700', '#0D0D20', '#0A0A18'],
    },
    {
      id: 'braids_coral',
      name: 'Coral & Cream',
      colors: {
        primary: '#E07050',
        secondary: '#FFF8F0',
        accent: '#F08070',
        background: '#FFFAF5',
        foreground: '#2A1510',
        muted: '#F5E8E0',
      },
      previewSwatch: ['#E07050', '#FFF8F0', '#FFFAF5'],
    },
    {
      id: 'braids_jade',
      name: 'Jade & Amber',
      colors: {
        primary: '#00A86B',
        secondary: '#FFBF00',
        accent: '#2ECC71',
        background: '#F5FFF8',
        foreground: '#0A2E18',
        muted: '#E0F5E8',
      },
      previewSwatch: ['#00A86B', '#FFBF00', '#F5FFF8'],
    },
  ],
};
