ALTER TABLE public.invitation_events
  ADD COLUMN comment_wall_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN comment_wall_reviewed_at timestamptz;

CREATE TABLE public.invitation_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES public.invitation_events(id) ON DELETE CASCADE,
  guest_name text NOT NULL CHECK (char_length(btrim(guest_name)) BETWEEN 1 AND 80),
  body text NOT NULL CHECK (char_length(btrim(body)) BETWEEN 1 AND 1000),
  is_hidden boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX invitation_comments_event_created_idx
  ON public.invitation_comments (event_id, created_at DESC, id DESC);

CREATE INDEX invitation_comments_public_event_created_idx
  ON public.invitation_comments (event_id, created_at DESC, id DESC)
  WHERE NOT is_hidden;

CREATE TABLE public.invitation_comment_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id uuid NOT NULL REFERENCES public.invitation_events(id) ON DELETE CASCADE,
  ip_hash text NOT NULL CHECK (ip_hash ~ '^[a-f0-9]{64}$'),
  content_hash text NOT NULL CHECK (content_hash ~ '^[a-f0-9]{64}$'),
  comment_id uuid NOT NULL REFERENCES public.invitation_comments(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX invitation_comment_submissions_lookup_idx
  ON public.invitation_comment_submissions (event_id, ip_hash, created_at DESC);

ALTER TABLE public.invitation_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invitation_comment_submissions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.invitation_comments, public.invitation_comment_submissions FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.submit_invitation_comment(
  p_event_id uuid,
  p_guest_name text,
  p_body text,
  p_ip_hash text,
  p_content_hash text
)
RETURNS TABLE (
  comment_id uuid,
  guest_name text,
  body text,
  created_at timestamptz,
  outcome text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_event public.invitation_events%ROWTYPE;
  v_duplicate_id uuid;
  v_recent_count integer;
  v_comment public.invitation_comments%ROWTYPE;
BEGIN
  IF p_ip_hash !~ '^[a-f0-9]{64}$' OR p_content_hash !~ '^[a-f0-9]{64}$' THEN
    RAISE EXCEPTION 'COMMENT_INVALID_HASH';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext(p_event_id::text),
    pg_catalog.hashtext(p_ip_hash)
  );

  SELECT event_row.* INTO v_event
  FROM public.invitation_events AS event_row
  WHERE event_row.id = p_event_id
  FOR UPDATE;

  IF NOT FOUND
    OR NOT v_event.comment_wall_enabled
    OR v_event.status NOT IN ('published', 'rsvp_closed')
    OR (v_event.expire_at IS NOT NULL AND v_event.expire_at <= pg_catalog.now())
    OR NOT EXISTS (
      SELECT 1 FROM public.invitation_owners AS event_owner
      WHERE event_owner.id = v_event.owner_id AND event_owner.is_active
    )
  THEN
    RAISE EXCEPTION 'COMMENT_WALL_CLOSED';
  END IF;

  DELETE FROM public.invitation_comment_submissions AS stale
  WHERE stale.event_id = p_event_id
    AND stale.ip_hash = p_ip_hash
    AND stale.created_at < pg_catalog.now() - pg_catalog.make_interval(days => 1);

  SELECT recent.comment_id INTO v_duplicate_id
  FROM public.invitation_comment_submissions AS recent
  WHERE recent.event_id = p_event_id
    AND recent.ip_hash = p_ip_hash
    AND recent.content_hash = p_content_hash
    AND recent.created_at >= pg_catalog.now() - pg_catalog.make_interval(mins => 2)
  ORDER BY recent.created_at DESC
  LIMIT 1;

  IF v_duplicate_id IS NOT NULL THEN
    SELECT comment_row.* INTO v_comment
    FROM public.invitation_comments AS comment_row
    WHERE comment_row.id = v_duplicate_id AND comment_row.event_id = p_event_id;
    IF FOUND THEN
      RETURN QUERY SELECT v_comment.id, v_comment.guest_name, v_comment.body, v_comment.created_at, 'duplicate'::text;
      RETURN;
    END IF;
  END IF;

  SELECT pg_catalog.count(*)::integer INTO v_recent_count
  FROM public.invitation_comment_submissions AS recent
  WHERE recent.event_id = p_event_id
    AND recent.ip_hash = p_ip_hash
    AND recent.created_at >= pg_catalog.now() - pg_catalog.make_interval(mins => 10);

  IF v_recent_count >= 5 THEN
    RAISE EXCEPTION 'COMMENT_RATE_LIMITED';
  END IF;

  INSERT INTO public.invitation_comments (event_id, guest_name, body)
  VALUES (p_event_id, pg_catalog.btrim(p_guest_name), pg_catalog.btrim(p_body))
  RETURNING * INTO v_comment;

  INSERT INTO public.invitation_comment_submissions (event_id, ip_hash, content_hash, comment_id)
  VALUES (p_event_id, p_ip_hash, p_content_hash, v_comment.id);

  RETURN QUERY SELECT v_comment.id, v_comment.guest_name, v_comment.body, v_comment.created_at, 'created'::text;
END;
$$;

REVOKE ALL ON FUNCTION public.submit_invitation_comment(uuid, text, text, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_invitation_comment(uuid, text, text, text, text) TO service_role;
